# Generated by Django 5.0.2 on 2024-03-21 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaints', '0003_alter_complaint_user'),
        ('User', '0004_alter_official_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.customuser'),
        ),
    ]
