# Generated by Django 5.0.2 on 2024-03-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_customuser_rename_username_official_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id',
            new_name='user_id',
        ),
    ]
