# Generated by Django 5.0.2 on 2024-03-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_official_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='official',
            old_name='user_name',
            new_name='username',
        ),
    ]
