# Generated by Django 5.0.2 on 2024-04-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_customuser_is_verified_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
